name: 🌐 JavaScript Builds
on: [push, pull_request, workflow_dispatch]

# Global Settings
env:
  GODOT_BASE_BRANCH: 3.4
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no optimize=size use_lto=yes disable_advanced_gui=yes module_arkit_enabled=no module_assimp_enabled=no module_bmp_enabled=no module_bullet_enabled=no module_camera_enabled=no module_csg_enabled=no module_dds_enabled=no module_enet_enabled=no module_etc_enabled=no module_fbx_enabled=no module_gdnative_enabled=no module_hdr_enabled=no module_jpg_enabled=no module_jsonrpc_enabled=no module_mbedtls_enabled=no module_minimp3_enabled=no module_mobile_vr_enabled=no module_ogg_enabled=no module_opensimplex_enabled=no module_opus_enabled=no module_pvr_enabled=no module_recast_enabled=no module_regex_enabled=no module_squish_enabled=no module_stb_vorbis_enabled=no module_svg_enabled=no module_tga_enabled=no module_theora_enabled=no module_tinyexr_enabled=no module_upnp_enabled=no module_vhacd_enabled=no module_visual_script_enabled=no module_vorbis_enabled=no module_webm_enabled=no module_webrtc_enabled=no module_websocket_enabled=no module_webxr_enabled=no module_xatlas_unwrap_enabled=no
  EM_VERSION: 2.0.25
  EM_CACHE_FOLDER: "emsdk-cache"

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-javascript
  cancel-in-progress: true

jobs:
  javascript-template:
    runs-on: "ubuntu-20.04"
    name: Template (target=release, tools=no)

    steps:
      - uses: actions/checkout@v2

      # Additional cache for Emscripten generated system libraries
      - name: Load Emscripten cache
        id: javascript-template-emscripten-cache
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{github.job}}

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: javascript
          target: release
          tools: false

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
